name: Android CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Install Rclone
      run: sudo apt-get update && sudo apt-get install -y rclone

    - name: Configure Rclone
      run: |
        mkdir -p ~/.config/rclone
        echo "${{ secrets.GDRIVE_CREDENTIALS }}" | base64 -d > sa.json
        echo "[gdrive]" > ~/.config/rclone/rclone.conf
        echo "type = drive" >> ~/.config/rclone/rclone.conf
        echo "service_account_file = $(pwd)/sa.json" >> ~/.config/rclone/rclone.conf
        echo "scope = drive" >> ~/.config/rclone/rclone.conf

    - name: Upload to Google Drive using Rclone
      run: |
        rclone copyto app/build/outputs/apk/debug/app-debug.apk gdrive:${{ secrets.GDRIVE_FOLDER_ID }}/IdeasTracker.apk \
        --drive-acknowledge-abuse \
        --drive-upload-cutoff 0 \
        --drive-chunk-size 128M \
        --drive-v2-download-min-size 0 \
        --drive-keep-revision-forever=false \
        --drive-impersonate ${{ secrets.GDRIVE_OWNER_EMAIL }} \
        -v
