name: Android CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Install Rclone
      run: sudo apt-get update && sudo apt-get install -y rclone

    - name: Configure Rclone
      run: |
        mkdir -p ~/.config/rclone
        cat << EOF > ~/.config/rclone/rclone.conf
        [gdrive]
        type = drive
        service_account_credentials = $(echo "${{ secrets.GDRIVE_CREDENTIALS }}" | base64 -d)
        scope = drive
        EOF

    - name: Upload to Google Drive using Rclone
      run: |
        rclone copyto app/build/outputs/apk/debug/app-debug.apk gdrive:${{ secrets.GDRIVE_FOLDER_ID }}/IdeasTracker.apk \
        --drive-acknowledge-abuse \
        --drive-keep-revision-forever=false \
        --drive-upload-cutoff 0 \
        -v
